name: CI

on:
  push:
    branches: [ pep517 ]

jobs:
  test:
    name: ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runs-on: windows-latest
        python:
          - name: PyPy 2.7
            tox: pypy27
            action: pypy-2.7
          - name: PyPy 3.6
            tox: pypy36
            action: pypy-3.6
          - name: PyPy 3.7
            tox: pypy37
            action: pypy-3.7
        task:
          - name: Test
            tox: tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - uses: twisted/python-info-action@v1.0.1

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: Test
      run: tox -vv -e ${{ matrix.python.tox }}-tests || true
    
    - name: Check
      run: tree /f .tox/${{ matrix.python.tox }}-tests

    